[package]
name = "dlq"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
sqlx = "0.8.3"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
